namespace Infonet.Reporting.Enumerations {
	public enum ClientReferralSourceEnum {
        ChildAdvocacyCenter = 0,
        CircuitClerk = 1,
        Clergy = 2,
        CenterHotline = 3,
        DCFS = 4,
        EducationSystem = 5,
        Friend = 6,
        Hospital = 7,
        HousingProgram = 8,
        IlLDVHelpline = 9,
        LegalSystem = 11,
        Media = 12,
        Medical = 13,
        MedicalAdvocacyProgram = 14,
        NationalDVHotline = 16,
        Police = 17,
        PrivateAttorney = 18,
        PublicHealth = 19,
        Relative = 20,
        Self =  21,
        SexualAssaultProgram =  22,
        SocialServicesProgram = 23,
        StateAttorney = 24,
        Other = 25,
        OtherDVProgram = 26,
        OtherLocalhotline =  27, 
        OtherRapeCrisisCenter = 29
    }
}