namespace Infonet.Reporting.Enumerations {
	public enum ReportTableHeaderEnum {
		New = 1,
		Ongoing,
		HIVAdultCount,
		HIVChildCount,
		DVShelterUse,
		HomelessServiceUse,
		Number,
		Percent,
		Male,
		Female,
		Other,
		NumberOfClientsReceivingServices,
		NumberOfContacts,
		HoursOfService,
		Hours,
		NumberOfClientsReceivingShelter,
		DaysOfShelterReceived,
		EventNumberOfEvents,
		EventNumberOfPeopleReached,
		EventHours,
		NumberOfClients,
		NumberOfPresentations,
		NumberOfParticipants,
		NumberOfStaff,
		PresentationHours,
		StaffConductHours,
		StaffTravelHours,
		StaffPreparationHours,
		PublicationNumberOfSegments,
		PublicationPrepareHours,
		PublicationStaffPrepareHours,
		HotlineNumberOfCalls,
		OutcomeTotalYes,
		OutcomeTotalNo,
		OutcomeTotalSurveys,
		OutcomeTotalRecords,
		OutcomeEligibleClientsServed,
		TurnAwayAdultCount,
		TurnAwayChildCount,
		TurnAwayReferralYes,
		TurnAwayReferralNo,
		InPersonContacts,
		CrisisInterventionPhoneContacts,
		Total = 999
	}
}
